# These are supported funding model platforms

patreon: secretlab
github: YarnSpinnerTool
custom: ['https://yarnspinner.itch.io', 'https://assetstore.unity.com/packages/tools/behavior-ai/yarn-spinner-for-unity-the-friendly-dialogue-and-narrative-tool-267061']
